version: '3'

services:
  db:
    build:
      context: .
      dockerfile: ./dbdocker/Dockerfile.db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nombre_de_tu_base_de_datos
      POSTGRES_USER: nombre_de_usuario
      POSTGRES_PASSWORD: contrase–a

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "3000:3000"
    depends_on:
      - db
