
# Utiliza una imagen base de PostgreSQL
FROM postgres:latest

# Variables de entorno para la configuraci—n de la base de datos
ENV POSTGRES_DB=mydatabase \
    POSTGRES_USER=myuser \
    POSTGRES_PASSWORD=mypassword

# Exp—n el puerto en el que PostgreSQL estar‡ escuchando
EXPOSE 5432
